package cmd

import (
	"os"
	"testing"
)

func TestParseDNSServers(t *testing.T) {
	t.Run("valid resolv.conf", func(t *testing.T) {
		tmpFile, err := os.CreateTemp("", "resolv-conf-*")
		if err != nil {
			t.Fatalf("failed to create temp file: %v", err)
		}
		defer os.Remove(tmpFile.Name())

		content := `# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
search example.com
`
		if _, err := tmpFile.WriteString(content); err != nil {
			t.Fatalf("failed to write: %v", err)
		}
		tmpFile.Close()

		servers, err := parseDNSServers(tmpFile.Name())
		if err != nil {
			t.Fatalf("parseDNSServers() returned error: %v", err)
		}

		if len(servers) != 2 {
			t.Fatalf("got %d servers, want 2", len(servers))
		}
		if servers[0] != "8.8.8.8" {
			t.Errorf("servers[0] = %q, want 8.8.8.8", servers[0])
		}
		if servers[1] != "8.8.4.4" {
			t.Errorf("servers[1] = %q, want 8.8.4.4", servers[1])
		}
	})

	t.Run("no nameservers", func(t *testing.T) {
		tmpFile, err := os.CreateTemp("", "resolv-empty-*")
		if err != nil {
			t.Fatalf("failed to create temp file: %v", err)
		}
		defer os.Remove(tmpFile.Name())

		content := `# Empty config
search example.com
`
		if _, err := tmpFile.WriteString(content); err != nil {
			t.Fatalf("failed to write: %v", err)
		}
		tmpFile.Close()

		_, err = parseDNSServers(tmpFile.Name())
		if err == nil {
			t.Error("parseDNSServers() should return error when no nameservers found")
		}
	})

	t.Run("file not found", func(t *testing.T) {
		_, err := parseDNSServers("/nonexistent/resolv.conf")
		if err == nil {
			t.Error("parseDNSServers() should return error for nonexistent file")
		}
	})
}
