on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          cgo_enabled: 0
          build_args: -ldflags "-s -w"
          build_tags: linux-amd64

  release-linux-arm64:
    name: release linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: arm64
          cgo_enabled: 0
          build_args: -ldflags "-s -w"
          build_tags: linux-arm64

  release-mac-arm64:
    name: release darwin/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: arm64
          cgo_enabled: 0
          build_args: -ldflags "-s -w"
          build_tags: darwin-arm64

  release-mac-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: amd64
          cgo_enabled: 0
          build_args: -ldflags "-s -w"
          build_tags: darwin-arm64
